### ISSUE TITLE
Add the option to translate Fastlane (app store details) in Weblate

### ISSUE THREAD

**Issue by lucasmz-dev** [onionshare/onionshare-android#127]

**Comment by LucasMZReal** [comment]
> because the F-Droid doesn't make an auto translation

Thankfully! I would be pretty sad if they did that to be honest; machine translation or bad translations makes things less accessible than just keeping it in the native language or English.

Right now, I can open a PR to add some metadata, and I suppose it would work, but it's very manual and I wouldn't be notified of changes and updates to the original string as what I can do with Weblate.

**Comment by lucasmz-dev** [comment]
After doing what I said above, I realize it's a bit more complicated, still I feel like it's possible to have at least the short and full description, and maybe title if that makes sense.

OnionShare has some graphics and images which are hard to translate; not sure if there's files to be able to do that or something. See #128.

**Comment by grote** [comment]
upstream source files seem to be here: https://codeberg.org/iNPUTmice/Conversations/src/branch/master/src/conversations/fastlane/metadata/android/en-US

We would need to check how to include this in weblate the same way. Maybe @emmapeel2 knows.

**Comment by emmapeel2** [comment]
> upstream source files seem to be here: https://codeberg.org/iNPUTmice/Conversations/src/branch/master/src/conversations/fastlane/metadata/android/en-US

To add to weblate is easy:  you need to create this folder structure in a repository, and we can hook it up to a new weblate component. I can do that under the OnionShare weblate project.

What I don´t know is where do you tell Fastlane to pick up the translations.

**Comment by lucasmz-dev** [comment]
I thought Fastlane just picked it up automatically?

**Comment by emmapeel2** [comment]
Oooooh, I see, the files are already in the repo (duh! I didn´t looked). I will add it to weblate, linked to the other components.

**Comment by emmapeel2** [comment]
OK, I have added the component to weblate, you can translate the metadata here: https://hosted.weblate.org/projects/onionshare/android-metadata/

It was very easy with weblate already supporting the format, and it is only one component instead of 4 little one-string components.

**Comment by lucasmz-dev** [comment]
Just in case, PT-BR translations are not yet showing up, I believe an app update (or something) triggers that.

**Comment by emmapeel2** [comment]
I guess new releases will provide the translations. Weblate is already submitting them to the repository: https://github.com/onionshare/onionshare-android/pull/126/files
