### ISSUE TITLE
Add support for themed app icons on Android 13+

### ISSUE THREAD

**Issue by icejuice-enjoyer** [onionshare/onionshare-android#130]
Adding support would help better integrate the app icon in launchers on Android 13+ devices.

https://developer.android.com/about/versions/13/features#themed-app-icons
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

**Comment by SpiritOTHawk** [comment]
Needed

**Comment by grote** [comment]
fixed in https://github.com/onionshare/onionshare-android/commit/2abe2534f86fe64278f247f45c259ec5eab52730
