### ISSUE TITLE
Feedback: Adding files does not work

### ISSUE THREAD

**Issue by grote** [onionshare/onionshare-android#34]
We have two reports from different people with Samsung devices that they select a file and then the app goes back to the main screen without anything happening.

Not sure if they are maybe not yet used to the system file picker and are not really selecting files or if there's a bug that causes us to not adding files properly.

The second feedback was made for the latest version of the app which already uses `OPEN_DOCUMENT` with `GET_CONTENT` as a fallback. The first report was still for a version when we were only using `GET_CONTENT`.

**Comment by akwizgran** [comment]
Is it possible that the system's running low on memory and killing the OnionShare process while it's in the background? Perhaps we could try manually killing the OnionShare process while the file picker's open to see whether the behaviour looks like what the users are reporting?

**Comment by grote** [comment]
Good idea! Unfortunately, when I use the don't keep activities option or kill the process while the file picker is open, the intent gets redelivered to the activity and the selected file added successfully.

When the list of Uris is empty like when the user presses the back button in the file selection dialog, we return silently from the method. Maybe we should show something instead to see if this is the case here?

**Comment by akwizgran** [comment]
Good call, maybe a "No files selected" toast or something that we can ask these users to watch out for, without annoying users who really intended to cancel the action?

**Comment by grote** [comment]
We do have this Toast now (#35) and didn't receive further feedback mentioning the Toast or inability to add files, so closing this.
