### ISSUE TITLE
Unable to open links created on Android

### ISSUE THREAD

**Issue by ingfabby** [onionshare/onionshare-android#43]
Tested on Galaxy S20, Android 11
Onion Share version: 0.1.5-alpha

Steps I followed:
1.- I opened the app
2.- Select an image to share
3.- Tap on start sharing
4.-Copied the link when it was ready
5.-I tried to open in on Tor Browser for Android and I got the following screen
![ima_611d2fb](https://user-images.githubusercontent.com/28932186/163214434-f93e6a1a-3d3d-4579-a862-7e6216443e89.png)
6.-I tried to open the link on Tor Browser Desktop and I got the following Screen
<img width="992" alt="Screen Shot 2022-04-13 at 10 15 28 AM" src="https://user-images.githubusercontent.com/28932186/163214377-1928e1a5-c81c-4755-bd61-741f0db5e452.png">

**Comment by grote** [comment]
Should be fixed by #56
