### ISSUE TITLE
Update foreground service notification text based on sharing state

### ISSUE THREAD

**Issue by bitmold** [onionshare/onionshare-android#44]
When you are starting to share a file and the app is in the "Starting... tap to cancel" state, the notification for Onion Share reads "Currently sharing files". 

Perhaps, when the app is in this state, it would be good for the notification to say "OnionShare is starting" and for it to have a "Cancel" action of its own.

Love the app so far btw <3 :)

**Comment by grote** [comment]
Thanks. Yeah we should update at least the notification text dependent on the current state.
