### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [onionshare/onionshare-android#63]
https://hosted.weblate.org/projects/onionshare/onionshare-android/#information
says "proprietary"

can be set to GPLv3-or-later in

https://hosted.weblate.org/settings/onionshare/onionshare-android
also
https://hosted.weblate.org/settings/onionshare/onionshare-ios

**Comment by grote** [comment]
ping @n8fr8! Alternatively, you can give me (@grote) access to the repo on weblate, so I can take of it.

**Comment by n8fr8** [comment]
Fixed it, but also gave you acess @grote

**Comment by comradekingu** [comment]
Top stuff
