### ISSUE TITLE
Location does not enable from the app

### ISSUE THREAD

**Issue by ingfabby** [onionshare/onionshare-android#70]
Tested on Galaxy S20, Android 12
Version 0.0.18-ALPHA-!

If you enable the location option from the app GPS coordinates are not captured, they are only captured if you manually go to the phone settings and enable location on the app permissions section of ProofMode.

**Comment by grote** [comment]
Onionshare does not have a location option and does not deal with GPS coordinates. Did you mean to open an issue for ProofMode? If so, you can do so here: https://github.com/guardianproject/proofmode-android/issues
