### ISSUE TITLE
Sharing files crashes when selecting the file

### ISSUE THREAD

**Issue by ingfabby** [onionshare/onionshare-android#72]
Version 0.1.8-alpha
Tested on:
Galaxy S20, Android 12
Galaxy A21, Android 10

The app crashes when I try to use the share option.
Steps to replicate
1.-Open the app
2.-Go to the "+" icon
3.-Select the image I want to share
4.-Tap on "Stat sharing"
5.-The message "Error An unexpected problem has occurred" appears.
6.-On the Galaxy S20 I also got the message 
"Clear Cache for OnionShare(alpha)?
OnionShare (alpha) closed because this app has a bug. Try cleaning the
app's cache first, and then reopen."
I did and I got the same result.
![Screenshot_20230116-223207_Device care](https://user-images.githubusercontent.com/28932186/212813734-8d276bda-a138-41a3-bd1e-cf3aa49401b2.jpg)
![Screenshot_20230116-224229_OnionShare (alpha) (1)](https://user-images.githubusercontent.com/28932186/212813738-9fb528ed-9c8a-400b-b4b7-c3fa3c89e5a0.jpg)

**Comment by grote** [comment]
Thanks for the report. Do you know how to collect a logcat by any chance?

**Comment by ingfabby** [comment]
The version on the nightly repo works:
https://raw.githubusercontent.com/onionshare/onionshare-android-nightly/master/fdroid/repo?fingerprint=7E04F902940A2AEDAC30E491A5CE7ADCC74A3F73B43459E4448222F3EEE629EF

**Comment by grote** [comment]
Great, then this was fixed by https://github.com/onionshare/onionshare-android/pull/74
