### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Xander-Be** [onionshare/onionshare-android#78]
Selected a .png of 256KB.

The ready light never changed from gray. (idk if it should)

Hit Start and  immediately errors out.  Did not see anything more specific as an error code.

Device:
moto g pure (XT2163DL)
Android 12     4.19.191+

**Comment by grote** [comment]
@Xander-Be could you please try again with latest version and see if this still happens?

**Comment by Xander-Be** [comment]
Installed app version 0.4.6.10.  Nothing has changed.
1) I add a .png file.
2) Wait for the Ready indicator to change from gray.
3) It never changed.
4) Hit Start 
5) An unexpected problem has occurred.

Also, Clear All and Remove do nothing at this point. I have to restart app to reset to process.

**Comment by grote** [comment]
We don't have an app version 0.4.6.10. Where did you see this version?

Latest version is `0.1.9-alpha`. Where did you get yours from? Our nightly repo or Google Play?

**Comment by Xander-Be** [comment]
Oh I see. I downloaded from Google Play. Says version 0.1.9-alpha on Google Play.

**Comment by Xander-Be** [comment]
@grote The latest version from Google Play works great on my device. Thanks. Will the app support web hosting in the future?

**Comment by grote** [comment]
Thanks, so it seems the initial issue was resolved.

> Will the app support web hosting in the future?

This isn't planned. What would be the use-case to host websites with mobile phones instead of a desktop computer?
