### ISSUE TITLE
Can't connect to onion service

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-android#95]
After successfully starting OnionShare and receiving an address, I am not able to connect to it using Tor Browser. The address tries loading but never fails (been trying for 10 mins with the progress bar still showing). 

Tested on a 6a. 
App downloaded from Aurora on 2023-07-22

**Comment by grote** [comment]
Ok, then this particular bug wasn't released, yet. What a relief :)

Anyway, I just pushed out version 0.1.13-alpha to Google Play which should be available later today. Could you please have a look if the issue persists with that version?

**Comment by grote** [comment]
@glenn-sorrentino any news?

**Comment by glenn-sorrentino** [comment]
> @glenn-sorrentino any news?

Just updated but still experiencing the issue.

**Comment by grote** [comment]
Wow that is weird! I guess you have `0.1.13-alpha` in your about dialog and from the same internet connection can connect to shares from onionshare desktop?

**Comment by grote** [comment]
Thanks Glenn. I've found the issue. This was only affecting release build and we only ever tested with debug build :facepalm: .

**Comment by grote** [comment]
@glenn-sorrentino can you please confirm that the latest `0.1.15-alpha` works now for you?
